//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.04.17 at 12:29:02 PM IST 
//


package training;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the training package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _Institute_QNAME = new QName("http://www.d2d.com/schemas/training", "institute");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: training
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Institute }
     * 
     */
    public Institute createInstitute() {
        return new Institute();
    }

    /**
     * Create an instance of {@link Course }
     * 
     */
    public Course createCourse() {
        return new Course();
    }

    /**
     * Create an instance of {@link Courses }
     * 
     */
    public Courses createCourses() {
        return new Courses();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Institute }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.d2d.com/schemas/training", name = "institute")
    public JAXBElement<Institute> createInstitute(Institute value) {
        return new JAXBElement<Institute>(_Institute_QNAME, Institute.class, null, value);
    }

}
