//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.04.17 at 12:29:02 PM IST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.d2d.com/schemas/training", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package training;
